# Generated by Django 6.0.6 on 2026-06-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider', models.CharField(max_length=255)),
                ('rating_score', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
            ],
        ),
    ]
