# Generated by Django 6.0.6 on 2026-06-05 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.CharField(max_length=255)),
                ('available_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tours.tour')),
            ],
            options={
                'db_table': 'tour_departures',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='tours.tourdeparture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
