# Generated by Django 6.0.6 on 2026-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_tourimage_touritinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description_tour_include',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
