# Generated by Django 6.0.6 on 2026-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_passenger_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
