# Generated by Django 6.0.6 on 2026-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_passenger_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('VERIFIED', 'Đã duyệt'), ('REJECTED', 'Bị từ chối')], default='PENDING', max_length=50),
        ),
    ]
