# Generated by Django 5.2.8 on 2026-06-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_alter_booking_status_alter_passenger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_hour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
