# Generated by Django 6.0.6 on 2026-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_booking_departure_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('discount_val', models.CharField(max_length=50)),
                ('discount_label', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('expiry', models.CharField(max_length=100)),
                ('status', models.CharField(default='Còn hiệu lực', max_length=50)),
                ('remaining_count', models.IntegerField(default=100)),
                ('color_hex', models.CharField(default='#319795', max_length=10)),
            ],
            options={
                'db_table': 'vouchers',
            },
        ),
    ]
