# Generated by Django 5.2.8 on 2026-06-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
