# Generated by Django 5.2.8 on 2026-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('CONFIRMED', 'Đã xác nhận'), ('CANCELLED', 'Đã hủy'), ('COMPLETED', 'Đã hoàn thành')], default='PENDING', max_length=50),
        ),
    ]
