# Generated by Django 5.2.8 on 2026-06-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_add_max_discount_to_voucher'),
        ('tours', '0012_alter_booking_status_review'),
    ]

    operations = [
    ]
