# Generated by Django 5.2.8 on 2026-06-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_merge_20260624_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
