# Generated by Django 5.2.8 on 2026-06-24 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_user_fcm_token'),
        ('tours', '0013_user_fcm_token_alter_review_rating'),
        ('tours', '0015_user_fcm_token'),
    ]

    operations = [
    ]
