# Generated by Django 5.2.8 on 2026-06-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_booking_customer_email_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdeparture',
            name='departure_hour',
            field=models.CharField(default='07:00', max_length=50),
        ),
    ]
