# Generated by Django 5.2.8 on 2026-06-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_tourdeparture_departure_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdeparture',
            name='departure_hour',
        ),
        migrations.AddField(
            model_name='tourdeparture',
            name='hour_departure',
            field=models.CharField(default='07:00, 17:00', max_length=255),
        ),
    ]
