# Generated by Django 6.0.6 on 2026-06-25 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0020_remove_tourdeparture_departure_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_data', models.TextField()),
                ('tour_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='tours.tourimage')),
            ],
            options={
                'db_table': 'tour_image_features',
            },
        ),
    ]
