# Generated by Django 6.0.6 on 2026-06-25 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0022_merge_userbehavior_and_tourimagefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbehavior',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='tours.user'),
        ),
    ]
