# Generated by Django 5.2.8 on 2026-06-30 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_user_fcm_token'),
        ('tours', '0023_tour_views_alter_userbehavior_user'),
    ]

    operations = [
    ]
