# Generated by Django 5.2.8 on 2026-06-30 04:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0024_merge_20260630_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='UUID duy nhất định danh phiên chat, gửi từ client', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Người dùng (nếu đã đăng nhập)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='tours.user')),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Người dùng'), ('assistant', 'Chatbot')], help_text="'user' hoặc 'assistant'", max_length=20)),
                ('content', models.TextField(help_text='Nội dung tin nhắn')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tin nhắn được tạo')),
                ('session', models.ForeignKey(help_text='Phiên chat chứa tin nhắn này', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tours.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
